FROM ubuntu:eoan

RUN apt-get update && apt-get install -y build-essential python3-pip cmake && rm -rf /var/lib/apt/lists/*

RUN pip3 install conan

ENV CONAN_NON_INTERACTIVE=1
RUN conan profile new --detect default && \
    conan profile update settings.compiler.libcxx=libstdc++11 default && \
    conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

RUN conan install cpprestsdk/2.10.14@bincrafters/stable --build=missing
